#!/bin/sh
 #check if commit lock exists and prevent commit
 if test -f "git_vivado_commit_lock"; then	
    echo "Please use the Vivado TCL console to commit the project properly. Or use git commit -n switch to ignore"  
	  exit 1				
 fi 						

